# global_vars:
#   - name: "slidecount"
#     type: "shell"
#     params:
#       cmd: "bash $CONFIG/slideCounter/counter.sh"

matches:
  - trigger: "/rfs"
    replace: "[reading from slide]"

  - trigger: "/rts"
    replace: "[referring to slide]"

  - trigger: "/rtb"
    replace: "[referring to board]"

  - trigger: "/rtc"
    replace: "[referring to code]"

  - trigger: "/w"
    replace: "[writing]"

  - trigger: "/l"
    replace: "[laugher]"

  # - trigger: "/s"
  #   replace: "(slide {{slidecount}})"
  #   word: true

  - trigger: "/sn"
    replace: "(slide "

  - trigger: "/sli"
    replace: "(slide change)"

  - trigger: "/qstu"
    replace: "[student question]"

  - trigger: "/astu"
    replace: "[student answer]"

  - trigger: "/ans"
    replace: "[answer]"

  - trigger: "/qn"
    replace: "[question]"

  - trigger: "/ia"
    replace: "[inaudible]"

  - trigger: "/?"
    replace: "_(?)"

  - trigger: ":time"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"

  - trigger: ":time"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d-%B-%Y"

  - trigger: ":time"
    replace: "{{mydatetime}}"
    vars:
      - name: mydatetime
        type: date
        params:
          format: "%d-%B-%Y %H:%M"

  - trigger: "/cc"
    replace: "{{context}}"
    vars:
      - name: context
        type: choice
        params:
          values:
            - "[inaudible]"
            - "(?)"
            - "[reading from slide]"
            - "[writing]"
            - "[referring to code]"
            - "[coding]"

  - trigger: "/sc"
    replace: "{{soundctx}}"
    vars:
      - name: soundctx
        type: choice
        params:
          values:
            - "[inaudible]"
            - "[student question]"
            - "[video playing]"
            - "[interruption]"
            - "[laughter]"
            - "[applause]"
            - "[phone notifcation sound]"
            - "[bell ringing]"
            - "[sigh]"
            - "[music in background]"
            - "[mic feedback]"
            - "[background chatter]"
            - "[whispering]"
            - "[silence]"
